#create database sql_powerbi;
use sql_powerbi;

select * from customers;
select * from orders;
select * from restaurants;

#1.	Display all completed orders along with customer name and restaurant name. 
select c.customer_name,r.restaurant_name,o.order_status from 
customers c join  orders o on c.customer_id=o.customer_id
join restaurants r on o.restaurant_id=r.restaurant_id where o.order_status="Completed";

#2.	Find the total revenue generated by each restaurant. 
select r.restaurant_name,sum(o.order_amount) as Revenue from 
orders o join restaurants r on r.restaurant_id=o.restaurant_id 
group by r.restaurant_name;

#3.	Show the total number of orders placed by each customer. 
select c.customer_id,c.customer_name,count(o.customer_id) as orders_Count from 
customers c left join orders o on c.customer_id=o.customer_id
group by c.customer_id,c.customer_name;
 
#4.	Find the average order amount for each city. 
select r.city,avg(o.order_amount) as avg_order_amount from 
restaurants r join orders o on r.restaurant_id=o.restaurant_id 
group by r.city;

#5.	Categorize orders as Low, Medium, and High based on order amount.
select *,if(order_amount>=800,"High",if(order_amount>=400,"Medium","Low")) as Cost_level from orders;

#6.	Display restaurants whose average order value is greater than the overall average order value. 
select r.restaurant_name,round(avg(o.order_amount)) as graterThen_avg_value from 
restaurants r join orders o on r.restaurant_id=o.restaurant_id 
group by r.restaurant_name having avg(o.order_amount)>(select avg(order_amount) from orders);

#7.	Find customers who have never placed any orders. 
SELECT c.customer_id, c.customer_name,o.customer_id
FROM customers c LEFT JOIN orders o on c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

#8.	Show the top 5 customers based on total spending. 
select o.customer_id,c.customer_name,sum(order_amount) as spend from 
orders o join customers c on c.customer_id=o.customer_id 
group by o.customer_id,c.customer_name order by spend desc limit 5;

#9.	Find the most frequently used payment method. 
select payment_method,count(payment_method) count from orders group by payment_method order by count desc limit 1;

#10.Calculate the running total of revenue by order date. 
with run as (
select order_date,sum(order_amount) as revenue from orders group by order_date
)select  *,sum(revenue) over(order by revenue) running_total from run;

#11.Rank restaurants based on total revenue generated
with rank_ as(
select r.restaurant_name,sum(o.order_amount) as revenue from orders o join restaurants r on r.restaurant_id=o.restaurant_id group by r.restaurant_name
)select *,rank() over(order by revenue desc) as ranking from rank_;

#12.Find the second highest order amount from the orders table. 
select max(order_amount) as sec_high from orders 
where order_amount < (select max(order_amount) from orders);
					#OR
SELECT DISTINCT order_amount,order_id
FROM orders ORDER BY order_amount DESC LIMIT 1, 1;

#13.Find customers who placed more orders than the average number of orders per customer. 
with tab as(
select c.customer_id,c.customer_name,count(o.order_id) count 
from customers c join orders o on c.customer_id=o.customer_id 
group by c.customer_id,c.customer_name
)select * from tab where count > (select avg(count) from tab);

#14.Display the top 3 restaurants in each city based on total orders received. 
select * from (select city,restaurant_name,count(order_id) as total_orders,
dense_rank() over(partition by city order by count(order_id) desc) as r
from restaurants join orders on restaurants.restaurant_id=orders.restaurant_id
group by city,restaurants.restaurant_id,restaurant_name) as temp
where r<=3;

#15.Calculate month-wise revenue and show the previous month revenue.
with temp as(
select monthname(order_date) month,sum(order_amount) as revenue from orders group by month
)select *,lag(revenue) over(order by month) as previous_month_revenue from temp;

ALTER TABLE orders
ADD COLUMN dish VARCHAR(50);

set sql_safe_updates=0;
UPDATE orders
SET dish =
CASE
    -- ₹150 - ₹299
    WHEN order_amount BETWEEN 150 AND 299 THEN
        ELT((order_id % 5)+1,
        'Idli',
        'Vada',
        'Veg Burger',
        'French Fries',
        'Falafel')

    -- ₹300 - ₹499
    WHEN order_amount BETWEEN 300 AND 499 THEN
        ELT((order_id % 5)+1,
        'Masala Dosa',
        'Veg Fried Rice',
        'Hakka Noodles',
        'Chicken Wrap',
        'Paneer Butter Masala')

    -- ₹500 - ₹699
    WHEN order_amount BETWEEN 500 AND 699 THEN
        ELT((order_id % 5)+1,
        'Chicken Biryani',
        'Veg Supreme Pizza',
        'Chicken Burger',
        'Chicken Shawarma',
        'Butter Chicken')

    -- ₹700 - ₹899
    WHEN order_amount BETWEEN 700 AND 899 THEN
        ELT((order_id % 5)+1,
        'Mutton Biryani',
        'Chicken Tikka',
        'Paneer Tikka',
        'Grilled Chicken',
        'Tandoori Chicken')

    -- ₹900 - ₹1200
    WHEN order_amount >= 900 THEN
        ELT((order_id % 5)+1,
        'Family Biryani',
        'Seafood Platter',
        'BBQ Chicken Combo',
        'Mutton Family Pack',
        'Special Combo Meal')
END;

alter table orders drop column dish;

select dish,count(dish) from orders group by dish;

ALTER TABLE orders
ADD COLUMN dish_url VARCHAR(500);

UPDATE orders
SET dish_url =
CASE dish
    WHEN 'Seafood Platter' THEN 'https://i.pinimg.com/1200x/f1/df/c0/f1dfc0186e1ccb21c570aecf97c2c161.jpg'
    WHEN 'Veg Burger' THEN 'https://i.pinimg.com/1200x/27/ab/5e/27ab5edd0885b823023a2b5ba47a1f04.jpg'
    WHEN 'Chicken Wrap' THEN 'https://i.pinimg.com/736x/f9/8b/e5/f98be52a517ecd0c411ea77face7e23a.jpg'
    WHEN 'Butter Chicken' THEN 'https://i.pinimg.com/1200x/98/28/26/982826a65014d342377c1dcd27541ca0.jpg'
    WHEN 'Family Biryani' THEN 'https://i.pinimg.com/736x/76/f0/8a/76f08acdfb37dbc826886f3b716fd33a.jpg'
    WHEN 'Vada' THEN 'https://i.pinimg.com/1200x/2d/b4/77/2db4776752d02a797abbc9479a0da903.jpg'
    WHEN 'Paneer Tikka' THEN 'https://i.pinimg.com/736x/99/92/30/9992307b4ef980f009d5cef49a104b1d.jpg'
    WHEN 'Paneer Butter Masala' THEN 'https://i.pinimg.com/736x/cd/18/67/cd18679d709328ea1347af0f30f748d5.jpg'
    WHEN 'Chicken Shawarma' THEN 'https://i.pinimg.com/1200x/32/d0/6c/32d06ceecb005e084979f16ddd6a9607.jpg'
    WHEN 'Chicken Biryani' THEN 'https://i.pinimg.com/736x/7f/74/6b/7f746b3e4b8f8146acc162f1203687ef.jpg'
    WHEN 'Hakka Noodles' THEN 'https://i.pinimg.com/736x/8f/1d/ba/8f1dba7a774591e767c12d6d04e89b81.jpg'
    WHEN 'Mutton Family Pack' THEN 'https://i.pinimg.com/1200x/a0/82/4a/a0824ab867756c5165af00168f2e0696.jpg'
    WHEN 'Masala Dosa' THEN 'https://i.pinimg.com/736x/16/e2/e0/16e2e0c3fec165099a89d8eca33018d7.jpg'
    WHEN 'Veg Fried Rice' THEN 'https://i.pinimg.com/1200x/3a/da/7f/3ada7f7e3e544730d099d627014d6202.jpg'
    WHEN 'Special Combo Meal' THEN 'https://i.pinimg.com/1200x/25/ad/42/25ad4232b0ed0e39074da807354e2eed.jpg'
    WHEN 'BBQ Chicken Combo' THEN 'https://i.pinimg.com/1200x/e5/73/01/e57301f58e2cc4db39d83e59972a1a5c.jpg'
    WHEN 'French Fries' THEN 'https://i.pinimg.com/736x/62/07/01/620701147f4cefd9d14fb91657601c31.jpg'
    WHEN 'Mutton Biryani' THEN 'https://i.pinimg.com/1200x/a0/82/4a/a0824ab867756c5165af00168f2e0696.jpg'
    WHEN 'Veg Supreme Pizza' THEN 'https://i.pinimg.com/736x/a0/38/0f/a0380fa11a863b0ac7a4c394ca3263d0.jpg'
    WHEN 'Tandoori Chicken' THEN 'https://i.pinimg.com/736x/91/c4/7a/91c47a7663f464a7b46f16d0def806d3.jpg'
    WHEN 'Grilled Chicken' THEN 'https://i.pinimg.com/1200x/2c/67/a7/2c67a7bb604a693d9999918c71014b7f.jpg'
    WHEN 'Chicken Burger' THEN 'https://i.pinimg.com/1200x/84/d2/45/84d245e9d2151abe3ed9bbf8fff8b587.jpg'
    WHEN 'Idli' THEN 'https://i.pinimg.com/736x/6e/ce/8d/6ece8d9a9ad234ea9813cd29397ae44f.jpg'
    WHEN 'Chicken Tikka' THEN 'https://i.pinimg.com/1200x/17/0d/3e/170d3e18d9f5a67d1fd12d0726277787.jpg'
    WHEN 'Falafel' THEN 'https://i.pinimg.com/1200x/e0/de/d7/e0ded7fee4fd735dfef4e470a812c03e.jpg'
END;